import 'package:d_and_d/models/character.dart';
import 'package:flutter/material.dart';

class CharacteristicsPage extends StatelessWidget {
  const CharacteristicsPage({Key? key, required this.character}) : super(key: key);
  final Character character;
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(15),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text("CHARACTERISTICS:",
            style: TextStyle(fontWeight: FontWeight.bold,
                fontSize: 17),),
          Text("Strength: ${character.characteristics.strength}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Dexterity: ${character.characteristics.dexterity}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Constitution: ${character.characteristics.constitution}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Wisdom: ${character.characteristics.wisdom}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Intelligence: ${character.characteristics.intelligence}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Charisma: ${character.characteristics.charisma}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),

          const Divider(
            color: Colors.grey,
            thickness: 1,
          ),
          const Text("\nSAVING THROWS:",
            style: TextStyle(fontWeight: FontWeight.bold,
                fontSize: 17),),
          Text("Strength: ${character.savingThrows.strength}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Dexterity: ${character.savingThrows.dexterity}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Constitution: ${character.savingThrows.constitution}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Wisdom: ${character.savingThrows.wisdom}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Intelligence: ${character.savingThrows.intelligence}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Charisma: ${character.savingThrows.charisma}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),

          const Divider(
            color: Colors.grey,
            thickness: 1,
          ),
          const Text("\nSKILLS:",
            style: TextStyle(fontWeight: FontWeight.bold,
                fontSize: 17),),
          Text("Athletics: ${character.skills.athletics}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Acrobatics: ${character.skills.acrobatics}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Sleight of hand: ${character.skills.sleightOfHand}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Stealth: ${character.skills.stealth}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Arcana: ${character.skills.arcana}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("History: ${character.skills.history}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Investigation: ${character.skills.investigation}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Nature: ${character.skills.nature}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Religion: ${character.skills.religion}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Animal handling: ${character.skills.animalHandling}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Insight: ${character.skills.insight}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Medicine: ${character.skills.medicine}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Perception: ${character.skills.perception}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Survival: ${character.skills.survival}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Deception: ${character.skills.deception}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Intimidation: ${character.skills.intimidation}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Performance: ${character.skills.performance}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),
          Text("Persuasion: ${character.skills.persuasion}",
            style: const TextStyle(height: 1.5,
                fontWeight: FontWeight.w400,
                fontSize: 17),),


        ],
      ),
    );
  }
}
